### ISSUE TITLE
К файлу "Rating Aggregation.ipynb"

### ISSUE THREAD

**Issue by spirovga** [smirnovevgeny/RekkoChallenge#1]
Хочу поблагодарить за решение!
В процессе разбора решения, остался непонятным один момент. Не могли бы вы объяснить, из каких соображений в "**_series_q75_**" и "**_multipart_q75_**" берутся квантили 50% и 20% соответственно?

**Comment by smirnovevgeny** [comment]
На самом деле там должны были быть везде 75-ые квантили. 
50-я и 20-я появились из-за экспериментов по смене стратегии агрегации рейтинга.
